add 3 tests for Juice Shop
dtyta/examTests pull request #1
Opened 2023-06-28 20:07 UTC by dtyta

2023-06-29 20:16 UTC, DmytroSanitarskyi requested changes

2023-06-29 20:16 UTC, DmytroSanitarskyi commented on cypress/support/helperAuth.js
> +cy.get('[id="mat-dialog-0"]').click();
тут потрібно пейдж обджект застосувати

2023-06-29 20:16 UTC, DmytroSanitarskyi commented on cypress/e2e/feedBackForm.cy.js
> +      cy.get("#captchaControl").type(captchaResult);
цей рядок і ті що нижче в пейдж обджект потрібно винести)

2023-06-29 20:16 UTC, DmytroSanitarskyi commented on cypress/e2e/juiceShop/buyingGoods.cy.js
> +beforeEach('Registration before authorization', () => {
якщо відновлюєш сессію з cy.restoreLocalStorage(); то перед кожним тестом тоді не потрібно реєструвати юзера. Щось одне потрібно видалити

2023-06-29 20:16 UTC, DmytroSanitarskyi commented on cypress/e2e/juiceShop/buyingGoods.cy.js
> +    cy.wait(500);
не використовуй цей вейт) для наступного кроку просто задай опцію {timeout: 1000}

2023-06-30 13:07 UTC, dtyta commented
@DmytroSanitarskyi підфіксив згідно коментарів

2023-06-30 20:18 UTC, DmytroSanitarskyi approved these changes
ідеально

2023-07-01 19:58 UTC, merged